### ISSUE TITLE
[Bug] LateInitializationError while login using credentials

### ISSUE THREAD

**Issue by icodelifee** [team-telnyx/telnyx-webrtc-flutter#11]
**Bug Category**
- [x] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [ ] Other

**SDK Version**
telnyx_webrtc: ^0.0.3

**Describe the bug**
LateInitializationError: Field '_socket@742383924' has not been initialized. while connecting with Credentials
<img width="989" alt="Screenshot 2022-08-18 at 12 21 05 AM" src="https://user-images.githubusercontent.com/18023153/185219446-2a0c9778-e92e-4d0d-ba36-35e497cfcbe1.png">
<img width="448" alt="Screenshot 2022-08-18 at 12 21 52 AM" src="https://user-images.githubusercontent.com/18023153/185219605-43aade2d-ad6f-46ed-9367-ae1583649cd4.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. e.g. (Log on with credentials)
2. e.g. (Socket error then returned)

** Device (please complete the following information):**
- OS Version: [Android 12]

**Logs**
Please provide any logs available to you, remember to enable verbose logging within the SDK.

**Comment by Oliver-Zimmerman** [comment]
Hi @icodelifee, is this in the sample application or in your own implementation? Can you confirm the same is happening in the sample application?

I will look into this issue as well as [this issue]( https://github.com/team-telnyx/telnyx-webrtc-flutter/issues/12) later today when I get a moment. 

Regards,
Oliver Zimmerman

**Comment by icodelifee** [comment]
> Hi @icodelifee, is this in the sample application or in your own implementation? Can you confirm the same is happening in the sample application?
> 
> I will look into this issue as well as [this issue](https://github.com/team-telnyx/telnyx-webrtc-flutter/issues/12) later today when I get a moment.
> 
> Regards, Oliver Zimmerman

This is happening in my own implementation, i haven't checked the example app.
It did work sometimes but im not able to get the audio or mic working, im not sure if the i have to do something else other than whats specified in the documentation to get the audio output and mic

**Comment by icodelifee** [comment]
@Oliver-Zimmerman i was able to fix this by adding a delay after connecting the client, so login happens after a small delay.
But im not getting any audio while calling

**Comment by Oliver-Zimmerman** [comment]
Hi @icodelifee, I'm not sure why the delay is necessary. Did you have a look at the sample implementation to see if you are doing something similar?

Regardless if it is working then that's great. I will close this for now and we can discuss Audio on the other ticket
