### ISSUE TITLE
[Bug] createCall() throws invalid argument error

### ISSUE THREAD

**Issue by icodelifee** [team-telnyx/telnyx-webrtc-flutter#12]
**Bug Category**
- [ ] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [x] Other

**SDK Version**
telnyx_webrtc: ^0.0.3

**Describe the bug**
While creating a call using connected Telnyx client throws Argument Error, looking into API I believe it is caused due to the #11 socket initialize error while logging with credentials, since it throws an error there, the socket id is not initialized.

**Logs**
```
I/flutter (13454): │ #0   TelnyxClient._onMessage (package:telnyx_webrtc/telnyx_client.dart:234:13)
package:telnyx_webrtc/telnyx_client.dart:234
I/flutter (13454): │ #1   TelnyxClient.connect.<anonymous closure> (package:telnyx_webrtc/telnyx_client.dart:89:9)
package:telnyx_webrtc/telnyx_client.dart:89
I/flutter (13454): │ 💡 DEBUG MESSAGE: {"jsonrpc":"2.0","id":30805,"method":"telnyx_rtc.ping","params":{"serno":1660818704}}
```
![Screenshot 2022-08-18 at 4 04 56 PM](https://user-images.githubusercontent.com/18023153/185375007-7902081a-68d8-4e5c-bcf6-53c49eada972.png)

**Comment by Oliver-Zimmerman** [comment]
@icodelifee 
Fixed: 
https://github.com/team-telnyx/telnyx-webrtc-flutter/pull/14

Please test with telnyx_webrtc: ^0.0.4
