### ISSUE TITLE
Add Speaker Button

### ISSUE THREAD

**Issue by hpsolver** [team-telnyx/telnyx-webrtc-flutter#9]
Could you please add speaker option on call screen.

**Comment by Oliver-Zimmerman** [comment]
@hpsolver please define the speaker option, do you mean you want a button that enables loudspeaker mode?   

As this is an example app feature, and not SDK related, this will likely not take priority but we will implement it when we have time.

**Comment by hpsolver** [comment]
okay thanks @Oliver-Zimmerman

**Comment by hpsolver** [comment]
@Oliver-Zimmerman can we handle call notifications in flutter using this plugin ?

**Comment by Oliver-Zimmerman** [comment]
It is possible, but not implemented in this sample app. Please see your other open issue where I have commented.

**Comment by hpsolver** [comment]
ok
